### ISSUE TITLE
깃 브랜치 전략 정하기

### ISSUE THREAD

**Issue by jsh9057** [MHC-1Day/1Day#2]
깃 브랜치 전략을 잡기

* [x] 깃 브랜치 전략 선택하기
* [x] 커밋에 이슈 넘버 붙이기 설명
* [x] 커밋 양식 정하기

* https://inpa.tistory.com/entry/GIT-⚡%EF%B8%8F-github-flow-git-flow-📈-브랜치-전략

**Comment by jsh9057** [comment]
github flow 브랜치 전략을 사용하기로 함

**Comment by 6loss0m** [comment]
git commit 양식도 정해야할 것 같습니돠. 👽

**Comment by jsh9057** [comment]
커밋 양식 정하기위해 이슈 오픈하겠습니다
